# orbs:
#   aws-ecr: circleci/aws-ecr@9.1.0
#   aws-cli: circleci/aws-cli@4.1.3
#   node: circleci/node@5.2.0

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@2.0.2

jobs:
  Deploy-React-App-On-EC2:
    machine:
      enabled: true
    steps:
      - run: 
          name: SSH_Into_EC2
          command: ssh ubuntu@3.235.164.190 './demo-react-ssh.sh';

version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-react-image:
          account-url: AWS_ECR_ACCOUNT_URL_REACT
          aws-access-key-id: ACCESS_KEY_ID_REACT
          aws-secret-access-key: SECRET_ACCESS_KEY_REACT
          dockerfile: Env/DockerFile
          path: .
          no-output-timeout: 20m
          region: AWS_REGION_REACT
          repo: AWS_ECR_REACT_REPO
          skip-when-tags-exist: false
          tag: latest,0.1$CIRCLE_BUILD_NUM
          filters:
            branches:
              only: main
          
      - Deployment-React-Approval:
          type: approval
          requires:
            - aws-ecr/build-and-push-react-image
          filters:
            branches: 
              only: main

      - Deploy-React-App-On-EC2:
          requires:
            - Deployment-React-Approval
          filters:
            branches:
              only: main







